USE master
GO

IF DB_ID('FINANCAS') IS NOT NULL
BEGIN
	ALTER DATABASE [FINANCAS] SET RESTRICTED_USER WITH ROLLBACK IMMEDIATE
	DROP DATABASE [FINANCAS]
END
GO

CREATE DATABASE [FINANCAS]
GO

ALTER DATABASE [FINANCAS] SET ALLOW_SNAPSHOT_ISOLATION ON
GO